# Generated by Django 5.2.4 on 2025-07-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='observations',
            field=models.ManyToManyField(blank=True, to='crmsolar.observation'),
        ),
        migrations.AddField(
            model_name='cpe',
            name='observations',
            field=models.ManyToManyField(blank=True, to='crmsolar.observation'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='observations',
            field=models.ManyToManyField(blank=True, to='crmsolar.observation'),
        ),
        migrations.AddField(
            model_name='task',
            name='observations',
            field=models.ManyToManyField(blank=True, to='crmsolar.observation'),
        ),
    ]
