# Generated by Django 5.2.4 on 2025-07-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsolar', '0002_observation_company_observations_cpe_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='observations',
        ),
        migrations.AddField(
            model_name='observation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='crmsolar.company'),
        ),
        migrations.AddField(
            model_name='observation',
            name='cpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='crmsolar.cpe'),
        ),
        migrations.AddField(
            model_name='observation',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='crmsolar.opportunity'),
        ),
        migrations.AddField(
            model_name='observation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='crmsolar.task'),
        ),
    ]
